<h1>Naive Bayes<h1>

Naive bayes is used in spam filtering, character recognization(text), weather prediction, face recognition, new article categorization

In [86]:
import pandas as pd 
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [87]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'], axis = 'columns', inplace = True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [88]:
target = df.Survived
inputs = df.drop('Survived', axis = 'columns')

When you want to use data that is string format, then you must convert it into a numeric values.
Here we can use two methods to convert them :
1. OneHotEncoding
2. using dummmies
for dummies use: 
df = pd.get_dummies(df, columns=['Sex'])
df = df.astype(int)

In [89]:
"""dummies = pd.get_dummies(inputs.Sex)
dummies.head()
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df.head()"""

#df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
dummies = pd.get_dummies(inputs.Sex)
dummies = dummies.astype(int)
dummies.head()

   female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [91]:
 inputs = pd.concat([inputs, dummies], axis = 'columns')
inputs.head()

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [92]:
inputs = inputs.loc[:, ~inputs.columns.duplicated()]
# to remove the duplicated columns use this
inputs.head()

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [94]:
inputs.columns[inputs.isna().any()]  #to find out if there are any Errors like having NaN

Index(['Age'], dtype='object')

In [95]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [96]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(10)

   Pclass     Sex        Age     Fare  female  male
0       3    male  22.000000   7.2500       0     1
1       1  female  38.000000  71.2833       1     0
2       3  female  26.000000   7.9250       1     0
3       1  female  35.000000  53.1000       1     0
4       3    male  35.000000   8.0500       0     1
5       3    male  29.699118   8.4583       0     1
6       1    male  54.000000  51.8625       0     1
7       3    male   2.000000  21.0750       0     1
8       3  female  27.000000  11.1333       1     0
9       2  female  14.000000  30.0708       1     0

In [97]:
inputs['Sex'] = inputs['Sex'].map({'male': 0, 'female': 1})
inputs

     Pclass  Sex        Age     Fare  female  male
0         3    0  22.000000   7.2500       0     1
1         1    1  38.000000  71.2833       1     0
2         3    1  26.000000   7.9250       1     0
3         1    1  35.000000  53.1000       1     0
4         3    0  35.000000   8.0500       0     1
..      ...  ...        ...      ...     ...   ...
886       2    0  27.000000  13.0000       0     1
887       1    1  19.000000  30.0000       1     0
888       3    1  29.699118  23.4500       1     0
889       1    0  26.000000  30.0000       0     1
890       3    0  32.000000   7.7500       0     1

[891 rows x 6 columns]

In [107]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size = 0.2)

In [108]:
print(len(X_train))
print(len(X_test))
print(len(inputs))

712
179
891

In [109]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model

GaussianNB()

In [110]:
model.fit(X_train, y_train)

GaussianNB()

In [111]:
model.score(X_test, y_test)

0.8212290502793296

In [112]:
X_test[:10]

     Pclass  Sex        Age      Fare  female  male
380       1    1  42.000000  227.5250       1     0
64        1    0  29.699118   27.7208       0     1
381       3    1   1.000000   15.7417       1     0
0         3    0  22.000000    7.2500       0     1
397       2    0  46.000000   26.0000       0     1
707       1    0  42.000000   26.2875       0     1
860       3    0  41.000000   14.1083       0     1
719       3    0  33.000000    7.7750       0     1
589       3    0  29.699118    8.0500       0     1
670       2    1  40.000000   39.0000       1     0

In [113]:
y_test[:10]

380    1
64     0
381    1
0      0
397    0
707    1
860    0
719    0
589    0
670    1
Name: Survived, dtype: int64

In [114]:
model.predict(X_test[:10])

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 1])