<h1>Naive Bayes<h1>

Naive bayes is used in spam filtering, character recognization(text), weather prediction, face recognition, new article categorization

In [2]:
import pandas as pd 
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [3]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'], axis = 'columns', inplace = True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [4]:
target = df.Survived
inputs = df.drop('Survived', axis = 'columns')

When you want to use data that is string format, then you must convert it into a numeric values.
Here we can use two methods to convert them :
1. OneHotEncoding
2. using dummmies

In [23]:
"""dummies = pd.get_dummies(inputs.Sex)
dummies.head()"""
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df

     Pclass  Sex   Age     Fare  Survived
0         3    0  22.0   7.2500         0
1         1    1  38.0  71.2833         1
2         3    1  26.0   7.9250         1
3         1    1  35.0  53.1000         1
4         3    0  35.0   8.0500         0
..      ...  ...   ...      ...       ...
886       2    0  27.0  13.0000         0
887       1    1  19.0  30.0000         1
888       3    1   NaN  23.4500         0
889       1    0  26.0  30.0000         1
890       3    0  32.0   7.7500         0

[891 rows x 5 columns]

In [8]:
 inputs = pd.concat([inputs, dummies], axis = 'columns')
inputs.head()

   Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False
3       1  female  35.0  53.1000    True  False
4       3    male  35.0   8.0500   False   True

In [9]:
inputs.columns[inputs.isna().any()]  #to find out if there are any Errors like having NaN

Index(['Age'], dtype='object')

In [10]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [12]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(10)

   Pclass     Sex        Age     Fare  female   male
0       3    male  22.000000   7.2500   False   True
1       1  female  38.000000  71.2833    True  False
2       3  female  26.000000   7.9250    True  False
3       1  female  35.000000  53.1000    True  False
4       3    male  35.000000   8.0500   False   True
5       3    male  29.699118   8.4583   False   True
6       1    male  54.000000  51.8625   False   True
7       3    male   2.000000  21.0750   False   True
8       3  female  27.000000  11.1333    True  False
9       2  female  14.000000  30.0708    True  False

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size = 0.3)

In [19]:
print(len(X_train))
print(len(X_test))
print(len(inputs))

623
268
891

In [21]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [22]:
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'male'