In [77]:
import pandas as pd 
import numpy as np

In [78]:
# A one dimensional array that can hold different types of data and has labels for each element
s = pd.Series() 
print("Pandas Series: ", s)  
data = np.array(['g', 'e', 'e', 'k', 's']) 
  
s = pd.Series(data) 
print("Pandas Series:\n", s)

Pandas Series:  Series([], dtype: object)
Pandas Series:
 0    g
1    e
2    e
3    k
4    s
dtype: object

In [79]:
   
df = pd.DataFrame() 
print(df)
lst = ['Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks'] 
  
df = pd.DataFrame(lst) 
print(df)

Empty DataFrame
Columns: []
Index: []
        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks

In [80]:
df = pd.DataFrame({
    'Hours': [2, 4, 6, 8, 7, 3],
    'marks': [30, 32, 77, 86, 73, 13],
    'Attendance': [60, 70, 75, 85, 78, 65],
    'Result': ['Fail', 'Fail', 'Pass', 'Pass', 'Pass', 'Fail']
})

In [81]:
ser = pd.Series(df['Hours']) 
data = ser.head(5)
data

0    2
1    4
2    6
3    8
4    7
Name: Hours, dtype: int64

In [82]:
data.loc[2:4]

2    6
3    8
4    7
Name: Hours, dtype: int64

In [83]:
data.iloc[2:4]

2    6
3    8
Name: Hours, dtype: int64

In [84]:
df.head()

   Hours  marks  Attendance Result
0      2     30          60   Fail
1      4     32          70   Fail
2      6     77          75   Pass
3      8     86          85   Pass
4      7     73          78   Pass

In [85]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Hours       6 non-null      int64
 1   marks       6 non-null      int64
 2   Attendance  6 non-null      int64
 3   Result      6 non-null      object
dtypes: int64(3), object(1)
memory usage: 324.0+ bytes
None

In [86]:
print(df.isnull().sum())
df = df.fillna(0)

Hours         0
marks         0
Attendance    0
Result        0
dtype: int64

In [87]:
ages = df[df['Attendance'] > 75]
print(ages)

   Hours  marks  Attendance Result
3      8     86          85   Pass
4      7     73          78   Pass

In [88]:
res = df.groupby('Result')['marks'].sum()
print(res)

Result
Fail     75
Pass    236
Name: marks, dtype: int64

In [89]:
data = np.array(['g','e','e','k','s','f', 'o','r','g','e','e','k','s'])
ser = pd.Series(data)

print(ser[5:])
print(ser[:5])

5     f
6     o
7     r
8     g
9     e
10    e
11    k
12    s
dtype: object
0    g
1    e
2    e
3    k
4    s
dtype: object

In [90]:
#Label-based Indexing
data = np.array(['g','e','e','k','s','f', 'o','r','g','e','e','k','s'])
ser = pd.Series(data,index=[10,11,12,13,14,15,16,17,18,19,20,21,22])

print(ser[16])

o

<b> Binary operations on Pandas Series <b>

In [91]:
ser1 = pd.Series([1, 2, 3], index=['A', 'B', 'C'])
ser2 = pd.Series([4, 5, 6], index=['A', 'B', 'C'])

df_sum = ser1.add(ser2)
print(df_sum)

df_sum = ser1.mul(ser2)
print(df_sum)

df_sum = ser1.div(ser2)
print(df_sum)
# other operations like sub(), sum(){Returns the sum of the values for the requested axis}, prod()
#mean(), pow(), abs(),cov()

A    5
B    7
C    9
dtype: int64
A     4
B    10
C    18
dtype: int64
A    0.25
B    0.40
C    0.50
dtype: float64

<b>Conversion operations on Series<b>

In [92]:
ser = pd.Series([1, 2, 3, 4])
ser = ser.astype(float)
print(ser)

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64

<b> Pandas CRUD operations <b>

In [93]:
# creating
data = {
    "Name": ["Ansh", "Sahil", "Ram"],
    "Age": [21, 20, 41],
    "City": ["Moradabad", "New Delhi", "Chennai"]
}
df = pd.DataFrame(data)
print(df)

# creating from lists
names = ["Akshit", "Uday", "Sam"]
ages = [25, 30, 35]
cities = ["Gurugram", "New Delhi", "Chicago"]

df = pd.DataFrame({
    "Name": names,
    "Age": ages,
    "City": cities
})

print(df)

    Name  Age       City
0   Ansh   21  Moradabad
1  Sahil   20  New Delhi
2    Ram   41    Chennai
     Name  Age       City
0  Akshit   25   Gurugram
1    Uday   30  New Delhi
2     Sam   35    Chicago

In [94]:
#reading a dataframe

print(df.head(3))
print('')
print(df.tail(3))
print('')
print(df.columns)
print('')
print(df.dtypes)
print('')
print(df.describe())
print('')

     Name  Age       City
0  Akshit   25   Gurugram
1    Uday   30  New Delhi
2     Sam   35    Chicago

     Name  Age       City
0  Akshit   25   Gurugram
1    Uday   30  New Delhi
2     Sam   35    Chicago

Index(['Name', 'Age', 'City'], dtype='object')

Name    object
Age      int64
City    object
dtype: object

        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [95]:
print(df["Name"])
print('')
print(df[["Name", "City"]])
print('')
print(df["City"].unique())
print('')
print(df[df["Age"] > 30])
print('')
print(df[(df["Age"] > 30) & (df["City"] == "SF")])

print(df[(df["Age"] > 30) | (df["City"] == "LA")])
print('')
print(df.iloc[0])

0    Akshit
1      Uday
2       Sam
Name: Name, dtype: object

     Name       City
0  Akshit   Gurugram
1    Uday  New Delhi
2     Sam    Chicago

['Gurugram' 'New Delhi' 'Chicago']

  Name  Age     City
2  Sam   35  Chicago

Empty DataFrame
Columns: [Name, Age, City]
Index: []
  Name  Age     City
2  Sam   35  Chicago

Name      Akshit
Age           25
City    Gurugram
Name: 0, dtype: object

In [96]:
print(df.iloc[0, 2])

Gurugram

In [97]:
print(df.iloc[1:3])

   Name  Age       City
1  Uday   30  New Delhi
2   Sam   35    Chicago

In [98]:
df.set_index("Name", inplace=True)

In [99]:
print(df.loc["Uday"])

Age            30
City    New Delhi
Name: Uday, dtype: object

<b>Modifying data in pandas<b>

In [100]:
data = {'Name': ['Eve', 'Jack', 'Charlie', 'Henry', 'John'],
        'Age': [25, 30, 35, 40, 45],
        'City': ['NY', 'LA', 'SF', 'Houston', 'Seattle']}
df = pd.DataFrame(data)
df

      Name  Age     City
0      Eve   25       NY
1     Jack   30       LA
2  Charlie   35       SF
3    Henry   40  Houston
4     John   45  Seattle

In [101]:
# Updating a single value
df.loc[df['Name'] == 'Jack', 'Age'] = 42

print(df)

      Name  Age     City
0      Eve   25       NY
1     Jack   42       LA
2  Charlie   35       SF
3    Henry   40  Houston
4     John   45  Seattle

In [102]:
#updating entire column
df['City'] = ['Boston', 'Chicago', 'LA', 'Austin', 'Miami']
df

      Name  Age     City
0      Eve   25   Boston
1     Jack   42  Chicago
2  Charlie   35       LA
3    Henry   40   Austin
4     John   45    Miami

In [103]:
# updating based on condition
df.loc[df['City'] == 'LA', 'Age'] = 31
df

      Name  Age     City
0      Eve   25   Boston
1     Jack   42  Chicago
2  Charlie   31       LA
3    Henry   40   Austin
4     John   45    Miami

<b>Deleting data in pandas<b>

In [104]:
data = {'Name': ['Eve', 'Jack', 'Charlie', 'Henry', 'John'],
        'Age': [25, 30, 35, 40, 45],
        'City': ['NY', 'LA', 'SF', 'Houston', 'Seattle']}
df = pd.DataFrame(data)

print(df)

      Name  Age     City
0      Eve   25       NY
1     Jack   30       LA
2  Charlie   35       SF
3    Henry   40  Houston
4     John   45  Seattle

In [105]:
#Deleting a column
df = df.drop('City', axis=1)
print(df)

      Name  Age
0      Eve   25
1     Jack   30
2  Charlie   35
3    Henry   40
4     John   45

In [110]:
#Deleting a Row
df = df.drop(2, axis=0) 
print(df)

NameError: name 'df' is not defined

In [107]:
#Deleting based on condition
df = df[df['Age'] != 35]
print(df)

    Name  Age
0    Eve   25
1   Jack   30
3  Henry   40
4   John   45

In [108]:
#Delete entire dataset
df = pd.DataFrame(data)

del df